# Exploratory data analysis (EDA) of car data

## Libraries and settings

In [2]:
# Libraries
import os
import random
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
from datetime import datetime, timedelta

# seaborn graphics settings
sns.set_theme(color_codes=True)

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Show current working directory
print(os.getcwd())

/workspaces/python_exploratory_data_analysis

## Importing the car data

### Importing the car data

In [3]:
# Columns to read
columns = ["Offer_Id",
            "Type",
            "Price",
            "HP",
            "Mileage",
            "Fuel_Type",
            "Transmission",
            "Dealer_PLZ",
            "Dealer_City",
            "Dealer_Street_House_Nr",
            "Init_Regist_MY",
            "Init_Regist_Month",
            "Init_Regist_Year",
            "Init_Regist_Dt"]

# Read and select variables
df_orig = pd.read_csv("autoscout24_data_enriched_cleaned.csv", sep=",")[columns]

# Change column names to lower case
df_orig.columns = df_orig.columns.str.lower()

# Remove duplicates
df_orig = df_orig.drop_duplicates()
df_orig.head(5)

# Remove missing values
df = df_orig.dropna()
df.head(5)

,offer_id,type,price,hp,mileage,fuel_type,transmission,dealer_plz,dealer_city,dealer_street_house_nr,init_regist_my,init_regist_month,init_regist_year,init_regist_dt
0,7324420,AUDI A5 Sportback 3.0 TDI quattro S-tronic (Li...,22500,245,75000,Diesel,Automatisiertes Schaltgetriebe,8488,Turbenthal,Mettlenstrasse 3,10.2014,10.0,2014.0,2014-10
1,7512768,MERCEDES-BENZ SLK 200 7G-Tronic (Cabriolet),23749,184,46655,Benzin,Automat sequentiell,3186,Düdingen,Brugerastrasse 60,6.2013,6.0,2013.0,2013-06
2,7512034,MERCEDES-BENZ C 350 Avantgarde 4Matic 7G-Troni...,18500,306,138955,Benzin,Automat sequentiell,1262,Eysins,1262 Eysins,6.2011,6.0,2011.0,2011-06
3,7512728,MERCEDES-BENZ A 45 AMG 4Matic Speedshift 7G-DC...,36000,360,43000,Benzin,Automatisiertes Schaltgetriebe,4314,Zeiningen,Am Stutz 21,8.2015,8.0,2015.0,2015-08
4,7490242,AUDI A5 Sportback 2.0 TFSI Sport quattro S-tro...,48500,252,43300,Benzin,Automatisiertes Schaltgetriebe,3250,Lyss,3250 Lyss,9.2018,9.0,2018.0,2018-09

## Univariate non-graphical exploratory data analysis (EDA)

### Quantiles

In [5]:
# Calculate Quantiles 
df[['price', 'hp', 'mileage']].quantile(
    q=[0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95]).round(2)

        price     hp   mileage
0.05   4000.0   90.0   13700.0
0.10   5900.0  110.0   23000.0
0.25  10900.0  150.0   45000.0
0.50  19900.0  204.0   83500.0
0.75  35900.0  306.0  130000.0
0.90  56900.0  405.0  176000.0
0.95  72500.0  469.5  206090.5

### Shape (number of rows and colums)

In [6]:
# Number of rows and columns
print (df.shape)

(3971, 14)

### Data types

In [7]:
# Show data types
df.dtypes

offer_id                    int64
type                       object
price                       int64
hp                          int64
mileage                     int64
fuel_type                  object
transmission               object
dealer_plz                  int64
dealer_city                object
dealer_street_house_nr     object
init_regist_my            float64
init_regist_month         float64
init_regist_year          float64
init_regist_dt             object
dtype: object

### Summary statistics of numeric variables

In [8]:
# Show summary statistics of variables
df.describe()

,offer_id,price,hp,mileage,dealer_plz,init_regist_my,init_regist_month,init_regist_year
count,3.971000e+03,3971.000000,3971.000000,3971.000000,3971.000000,3971.000000,3971.000000,3971.000000
mean,7.242907e+06,27527.641652,235.831025,92952.412491,5522.633594,6.510513,6.309494,2010.189121
std,4.655890e+05,26670.221155,119.671388,61097.990134,2848.337824,3.386338,3.386320,9.610067
min,1.395491e+06,160.000000,16.000000,1.000000,1000.000000,1.194600,1.000000,1929.000000
25%,7.249691e+06,10900.000000,150.000000,45000.000000,3014.000000,3.201800,3.000000,2008.000000
50%,7.408668e+06,19900.000000,204.000000,83500.000000,6003.000000,6.201400,6.000000,2013.000000
75%,7.456806e+06,35900.000000,306.000000,130000.000000,8304.500000,9.201500,9.000000,2016.000000
max,7.512843e+06,428000.000000,772.000000,370000.000000,9657.000000,12.201900,12.000000,2020.000000

### Statistical measures (min, max, std, mean, median, count) for selected variables

In [10]:
# Price
print('price:',
      'count:', round(df['price'].count(), 1),      #diesr Code definiert die Ausgabe der Statistik für die Spalte 'price'
      'min:', round(df['price'].min(), 1),          #dieser Code definiert die minimale Ausgabe der Statistik für die Spalte 'price'
      'max:', round(df['price'].max(), 1),          #dieser Code definiert die maximale Ausgabe der Statistik für die Spalte 'price'
      'mean:', round(df['price'].mean(), 1),        #dieser Code definiert die durchschnittliche Ausgabe der Statistik für die Spalte 'price'
      'median:', round(df['price'].median(), 1),    #dieser Code definiert die mittlere Ausgabe der Statistik für die Spalte 'price'
      'std:', round(df['price'].std(), 1))          #dieser Code definiert die Standardabweichung der Ausgabe der Statistik für die Spalte 'price'

# Area
print('area:',
      'count:', round(df.mileage.count(), 1),      #diesr Code definiert die Ausgabe der Statistik für die Spalte 'mileage'
      'min:', round(df.mileage.min(), 1),          #dieser Code definiert die minimale Ausgabe der Statistik für die Spalte 'mileage'
      'max:', round(df.mileage.max(), 1),          #dieser Code definiert die maximale Ausgabe der Statistik für die Spalte 'mileage'
      'mean:', round(df.mileage.mean(), 1),       #dieser Code definiert die durchschnittliche Ausgabe der Statistik für die Spalte 'mileage'
      'median:', round(df.mileage.median(), 1),   #dieser Code  definiert die mittlere Ausgabe der Statistik für die Spalte 'mileage'
      'std:', round(df.mileage.std(), 1))         #dieser Code definiert die Standardabweichung der Ausgabe der Statistik für die Spalte 'mileage'

price: count: 3971 min: 160 max: 428000 mean: 27527.6 median: 19900.0 std: 26670.2
area: count: 3971 min: 1 max: 370000 mean: 92952.4 median: 83500.0 std: 61098.0

### Skewness

In [11]:
# Show skewness of selected variables
df[['price', 'hp', 'mileage']].skew()

#die Skewness bezeichnet die Asymmetrie einer Wahrscheinlichkeitsverteilung um ihren Mittelwert.

price      4.077049
hp         1.093046
mileage    0.886538
dtype: float64

### Kurtosis

In [12]:
# Show kurtosis of selected variables
df[['price', 'hp', 'mileage']].kurtosis()

#die Kurtosis beschreibt die Wölbung einer Wahrscheinlichkeitsverteilung im Vergleich zu einer Normalverteilung.

price      36.506763
hp          1.226153
mileage     0.739533
dtype: float64

### Extreme values

In [ ]:
# Low costs cars
df[df['price'] <=500]

#mit dieser Funktion werden alle Autos mit einem Preis von weniger als oder gleich 500 angezeigt

,offer_id,type,price,hp,mileage,fuel_type,transmission,dealer_plz,dealer_city,dealer_street_house_nr,init_regist_my,init_regist_month,init_regist_year,init_regist_dt
1651,7452246,FIAT Punto 1.4 16V Sporting (Kleinwagen),500,95,127600,Benzin,Schaltgetriebe manuell,2000,Neuchâtel,Rue Léon-Berthoud 14,7.2004,7.0,2004.0,2004-07
3704,7372156,VW Golf Variant 1800 Rolling Stones (Kombi),160,90,217650,Benzin,Schaltgetriebe manuell,1426,Concise,Aux Petits Prés 1,10.1995,10.0,1995.0,1995-10
3905,7510439,VOLVO V70 2.5 T XC AWD Nordic (Kombi),400,193,253000,Benzin,Automat,9553,Bettwiesen,Hauptstrasse 51,1.1999,1.0,1999.0,1999-01

In [15]:
# Very expansive cars
df[df['price'] >=250000]

#mit dieser Funktion werden alle Autos mit einem Preis von mehr als oder gleich 250000 angezeigt

,offer_id,type,price,hp,mileage,fuel_type,transmission,dealer_plz,dealer_city,dealer_street_house_nr,init_regist_my,init_regist_month,init_regist_year,init_regist_dt
312,6978696,LAMBORGHINI Aventador S LP740-4 Roadster E-Gea...,384900,741,4000,Benzin,Automatisiertes Schaltgetriebe,8008,Zürich,8008 Zürich,6.2018,6.0,2018.0,2018-06
1621,6395032,PORSCHE 911 GT2 RS (Coupé),428000,620,8900,Benzin,Schaltgetriebe manuell,1628,Vuadens,Route principale 144,1.2011,1.0,2011.0,2011-01
1824,5887777,MERCEDES-BENZ 220 SE (Cabriolet),255000,120,1200,Benzin,Schaltgetriebe manuell,6052,Hergiswil,Sonnenbergstrasse 9,7.1960,7.0,1960.0,1960-07
2714,7448261,PORSCHE 911 Speedster Manual Gearbox Chalk whi...,379000,510,14,Benzin,Schaltgetriebe,1004,Lausanne,.,3.2020,3.0,2020.0,2020-03
3876,6768872,McLAREN 675LT Coupé 3.8 V8 SSG (Coupé),280000,675,11500,Benzin,Automatisiertes Schaltgetriebe,1202,Geneve,1202 Geneve,3.2016,3.0,2016.0,2016-03

### Get a list of categories of categorical variable

In [15]:
# Get a list of categories of the variable fuel_type

## Multivariate non-graphical exploratory data analysis (EDA)

### Cross-tabulation

In [16]:
# Create a crosstab of the variables fuel_type and transmission

### Pivot tables

In [17]:
# Using pivot_table with averages of price, mileage and hp of the cars by fuel type

### Correlation matrix

In [18]:
# Calculate correlation matrix of the variables mileage, price and hp

### Covariance matrix

In [19]:
# Calculate covariance matrix of the variables mileage, price and hp

## Univariate graphical exploratory data analysis (EDA)

### Line chart (matplotlib)

In [21]:
# Generate time series data for mean car prices over the last 20 years



# Start from 25 years ago with an initial price



# Create a DataFrame to display the data



# Create figure


# Show plot

### Boxplot (seaborn)

In [ ]:
# Create a boxplot of the variable mileage

### Histogram  (matplotlib)

In [ ]:
# Plot Histogram of the variable price


# Create figure


# Set labels


# Set fontsize of tick labels


# Show plot

### Density plot  (seaborn)

In [ ]:
# Create a density plot of the variable price


# Create figure


# Set title and labels


# Show plot

### Quantile-Quantile (QQ-) plot

In [ ]:
# Create qqplot of the variable mileage


# Variable (standardized)

    
# Plot

### Barchart  (matplotlib)

In [ ]:
# Group data by fuel_type (only the topmost 15 values are shown)


# Values for barchart


# Figure


# Show graph

### Piechart (matplotlib)

In [ ]:
# Subset of cars with fuel type (only Diesel, Benzin and Elektro)


# Group data by  (only the 8 most frequently occurencies)


# Simple bar chart


# Show plot

## Multivariate graphical exploratory data analysis (EDA)

### Scatterplot (matplotlib)

In [ ]:
# Create a scatterplot of the variables hp and price

### Scatterplot (matplotlib) with regression line

In [ ]:
# Create a scatterplot of the variables hp and price


# Add a regression line (b = slope, a=intercept) to the plot


# Show plot

### Scatterplot-matrix (seaborn)

In [ ]:
# Create a scatterplot of the variables mileage, price and hp


# Show plot

### Hexagonal binning plot  (matplotlib)

In [ ]:
# Subset of cars with price <= 100000 and hp <= 400


# Create a scatterplot of the variables hp and price


# Set axes labels


# Show plot

### Correlation heatmap (seaborn)

In [ ]:
# Create correlation matrix with variable price, mileage and hp


# Plot heatmap

### Bubble plot (seaborn)

In [ ]:
# Create a scatterplot of the variables mileage, price, hp, price_per_hp
# price on the y-axis
# hp on the x-axis
# price_per_hp determines bubble size
# mileage determines color

### Jupyter notebook --footer info-- (please always provide this at the end of each notebook)

In [ ]:
import os
import platform
import socket
from platform import python_version
from datetime import datetime

print('-----------------------------------')
print(os.name.upper())
print(platform.system(), '|', platform.release())
print('Datetime:', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print('Python Version:', python_version())
print('-----------------------------------')