# Arbeitspaket (AP) 2: Advanced Data Preparation & Exploratory Data Analysis (EDA)

### Persönliche Angaben (bitte ergänzen)

<table>
  <tr>
    <td>Vorname:</td>
    <td></td>
  </tr>
  <tr>
    <td>Nachname:</td>
    <td></td>
  </tr>
  <tr>
    <td>Immatrikulationsnummer:</td>
    <td></td>
  </tr>
  <tr>
    <td>Modul:</td>
    <td>Data Science</td>
  </tr>
  <tr>
    <td>Prüfungsdatum / Raum / Zeit:</td>
    <td>10.11.2025 / Raum: MU O2.001 / 8:00 – 11:45</td>
  </tr>
  <tr>
    <td>Erlaubte Hilfsmittel:</td>
    <td>w.MA.XX.DS.24HS (Data Science)<br>Open Book, Eigener Computer, Internet-Zugang</td>
  </tr>
  <tr>
  <td>Nicht erlaubt:</td>
  <td>Nicht erlaubt ist der Einsatz beliebiger Formen von generativer KI (z.B. Copilot, ChatGPT) <br> sowie beliebige Formen von Kommunikation oder Kollaboration mit anderen Menschen.</td>
</tr>
</table>

## Bewertungskriterien

### <b style="color: gray;">(max. erreichbare Punkte: 40)</b>

<table>
  <thead>
    <tr>
      <th>Kategorie</th>
      <th>Beschreibung</th>
      <th>Punkteverteilung</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Code nicht lauffähig oder Ergebnisse nicht sinnvoll</td>
      <td>Der Code enthält Fehler, die verhindern, dass er ausgeführt werden kann (z.B. Syntaxfehler) oder es werden Ergebnisse ausgegeben, welche nicht zur Fragestellung passen.</td>
      <td>0 Punkte</td>
    </tr>
    <tr>
      <td>Code lauffähig, aber mit gravierenden Mängeln</td>
      <td>Der Code läuft, aber die Ergebnisse sind aufgrund wesentlicher Fehler unvollständig (z.B. fehlerhaftes Erstellen von Subsets der Daten). Nur geringer Fortschritt erkennbar.</td>
      <td>25% der max. erreichbaren Punkte</td>
    </tr>
    <tr>
      <td>Code lauffähig, aber mit mittleren Mängeln</td>
      <td>Der Code läuft und liefert teilweise korrekte Ergebnisse, aber es gibt grössere Fehler (z.B. Datenvisualisierungen entsprechen nicht den Vorgaben gemäss Fragestellung). Die Ergebnisse sind nachvollziehbar, aber unvollständig oder ungenau.</td>
      <td>50% der max. erreichbaren Punkte</td>
    </tr>
    <tr>
      <td>Code lauffähig, aber mit minimalen Mängeln</td>
      <td>Der Code läuft und liefert ein weitgehend korrektes Ergebnis, aber kleinere Fehler (z.B. Achsenbeschriftung oder Titel in Graphik fehlt) beeinträchtigen die Vollständigkeit des Ergebnisses.</td>
      <td>75% der max. erreichbaren Punkte</td>
    </tr>
    <tr>
      <td>Code lauffähig und korrekt</td>
      <td>Der Code läuft einwandfrei und liefert das korrekte Ergebnis ohne Mängel.</td>
      <td>100% der max. erreichbaren Punkte</td>
    </tr>
  </tbody>
</table>

## Python Libraries und Settings

In [1]:
# Libraries
import os
import re
import random
import sqlite3
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
from datetime import datetime, timedelta
from sqlalchemy import create_engine, text

# seaborn graphics settings
sns.set_theme(color_codes=True)

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Show current working directory
print(os.getcwd())

/workspaces/python_exploratory_data_analysis/LN2_AP02

## <b>Vorbereitung (Dieser Teil wird <u>nicht</u> bewertet!)</b>

#### <b>1.) Starten Sie eine GitHub Codespaces Instanz auf Basis Ihres Forks des folgenden GitHub Repositories:</b>

##### GitHub-Repository: https://github.com/mario-gellrich-zhaw/python_exploratory_data_analysis

## <b>Aufgaben (Dieser Teil wird bewertet!)</b>
<b>Hinweise zu den folgenden Aufgabenstellungen:</b>
<ul>
  <li>Beachten Sie auch die zu jeder Aufgabenstellung zugehörenden Details zu Aufgabenstellung.</li>
  <li>Lösen Sie jede Aufgabe mit Hilfe von Python Code. Integrieren Sie den Python Code in die Code-Zellen der jeweiligen Aufgabe.</li>
  <li>Stellen Sie die Lösung(en) jeder Aufgabe ganz oder in Teilen (z.B. erste 5 Zeilen) eines DataFrames im Jupyter Notebook dar.</li>
  <li>Stellen Sie sämtliche von Ihnen erstellte Graphiken im Jupyter Notebook dar.</li>
</ul>

#### <b>Aufgabe (1): Lesen Sie den Datensatz 'bicycle_data.json' aus dem Order 'Data' ein, und speichern Sie diesen in einem pandas DataFrame.</b>
<b>Details zur Aufgabenstellung:</b>
- Zeigen Sie die Dimension des DataFrames (Zeilen und Spalten) im Jupyter Notebook an.
- Zeigen Sie die Datentypen sämtlicher Spalten des DataFrames im Jupyter Notebook an.
- Zeigen Sie die ersten Zeilen des DataFrames im Jupyter Notebook an.

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [2]:
# Einlesen der Daten aus dem Order 'Data' in ein DataFrame 'df'
df = pd.read_csv('./Data/bicycle_data.csv',
                   sep=';', 
                   encoding='utf-8')

# Anzeigen der Dimension des DataFrames (Zeilen und Spalten)
print(f'Anzahl Zeilen: {df.shape[0]}; Anzahl Spalten: {df.shape[1]}', '\n')

# Anzeigen der Datentypen sämtlicher Spalten des DataFrames
print('Datentypen:\n', df.dtypes, '\n')

# Anzeigen der ersten 5 Zeilen des DataFrames
df.head(5)

Anzahl Zeilen: 5000; Anzahl Spalten: 13

Datentypen:
 offer_id                   int64
dealer_plz                 int64
dealer_city               object
dealer_street_house_nr    object
make                      object
model                     object
price_raw                 object
gear_count_raw            object
battery_life_raw          object
frame_size_raw            object
wheel_size_raw            object
is_ebike                   int64
description_raw           object
dtype: object

,offer_id,dealer_plz,dealer_city,dealer_street_house_nr,make,model,price_raw,gear_count_raw,battery_life_raw,frame_size_raw,wheel_size_raw,is_ebike,description_raw
0,57555186,8617,Zürich,Steinenvorstadt 104,Giant,Explore E+ 2,CHF 3420.-,12 Gänge,97 km,58 cm,27.5 Zoll,1,Vielseitiges E-Bike mit komfortabler Sitzposit...
1,95084884,6207,Basel,Kellerstrasse 79,Cube,Kathmandu Hybrid Pro,CHF 3420.-,12 Gänge,92 km,47 cm,28 Zoll,1,E-Trekkingbike mit Bosch Performance CX Motor ...
2,40161480,1232,Baar,Sonnenbergstrasse 120,Cube,Kathmandu Hybrid Pro,CHF 3240.-,12 Gänge,95 km,49 cm,29 Zoll,1,E-Trekkingbike mit Bosch Performance CX Motor ...
3,67448336,3690,Luzern,Weberstrasse 10,Bulls,E-Stream EVO AM 4,CHF 3670.-,10 Gänge,143 km,46 cm,27.5 Zoll,1,Hochwertiges E-Mountainbike mit ausgezeichnete...
4,84304232,2975,St. Gallen,Kellerstrasse 110,Trek,Domane SL 6,CHF 1770.-,22 Gänge,NaN,56 cm,27.5 Zoll,0,Leichtes Carbon-Rennrad mit hervorragender Däm...

<div>

#### <b> Hinweis! 

#### Falls Sie den Datensatz 'bicycle_data.json' nicht einlesen konnten, verwenden Sie die SQLite DB 'bicycle_data.db' im Order 'Data'.</b>

#### <b>Der folgende Python-Code liesst die Daten aus der SQLite DB in ein pandas DataFrame mit dem Namen 'df'.</b>

#### <b>Erstellen Sie dazu im Jupyter Notebook eine neue Code-Zelle unter dieser Markdown-Zelle und lassen den Code laufen.</b>

```python
# Engine für Datenbankverbindung erstellen
engine = create_engine('sqlite:///./Data/bicycle_data.db')

# SQL Abfrage
df = pd.read_sql_query("""SELECT * FROM bicycle_data""",
                          con=engine)

# Schliessen der Datenbankverbindung
engine.dispose()

# Anzeigen des DataFrames (erste 5 Zeilen)
df.head()
```
</div>

#### <b>Aufgabe (2): Extrahieren Sie die numerischen Werte der folgenden Variablen, und speichern Sie diese in separaten Variablen im DataFrame ab.</b>
<b>Details zur Aufgabenstellung:</b>
- Extrahieren Sie die numerischen Werte der folgenden Variablen, und speichern Sie diese in separaten Variablen ab:
  - price_raw
  - gear_count_raw
  - battery_life_raw
  - frame_size_raw
  - wheel_size_raw<br>
- Benennen Sie die Spalten der neuen Variablen folgendermassen (in Klammern ist der Datentyp angegeben):
  - price (Int64)
  - gear_count (Int64)
  - battery_life (Int64)
  - frame_size (Int64)
  - wheel_size (Float64)
- Stellen Sie ein Subset des DataFrames nur mit den neuen Spalten und den ersten 5 Zeilen im Jupyter Notebook dar.<br><br>

- Tipp: Die folgenden Code Zeilen inkl. regular expressions sind eine Hilfestellung zum Lösen der Aufgabe:
  ```python
    d1 = re.findall("CHF\s*(\d+)\.-", i)
    d1 = re.findall("(\d+)\s*Gänge", i)
    d1 = re.findall("(\d+)\s*km", str(i))
    d1 = re.findall("(\d+)\s*cm", i)
    d1 = re.findall("(\d+(?:[.,]\d+)?)", i)
  ```
- Gross- und Kleinschreibung beim Abspeichern als neue Variable beachten, z.B.:
  - df['my_int_var'] = pd.Series(my_int_var, dtype="Int64") -> kann mit NAs umgehen
  - df['my_float_var'] = pd.Series(my_float_var, dtype="Float64") -> kann mit NAs umgehen
  
<b style="color: gray;">(max. erreichbare Punkte: 8)</b>

In [15]:
# Extrahieren der numerischen Werte aus 'price_raw' und speichern in separaten Variablen
price = []
for i in df['price_raw']:                       
    d1 = re.findall("CHF\s*(\d+)\.-", i)       
    try:
        d2= int(''.join(d1))                    
    except:
        d2 = None                               
    price.append(d2)        

# Save as new variable in the pandas data frame
df['price'] = pd.Series(price, dtype='int64')

In [26]:
# Extrahieren der numerischen Werte aus 'gear_count_raw' und speichern in separaten Variablen
gears = []
for i in df['gear_count_raw']:                       
    d1 = re.findall("(\d+)\s*Gänge", i)       
    try:
        d2= int(''.join(d1))                    
    except:
        d2 = None                               
    gears.append(d2)        

# Save as new variable in the pandas data frame
df['gear_count'] = pd.Series(gears, dtype='int64')

In [31]:
# Extrahieren der numerischen Werte aus 'battery_life_raw' und speichern in separaten Variablen
battery = []
for i in df['battery_life_raw']:                       
    d1 = re.findall("(\d+)\s*km", str(i))       
    try:
        d2= float(''.join(d1))                    
    except:
        d2 = None                               
    battery.append(d2)        

# Save as new variable in the pandas data frame
df['battery_life'] = pd.Series(battery, dtype='float64')

In [27]:
# Extrahieren der numerischen Werte aus 'frame_size_raw' und speichern in separaten Variablen
frame = []
for i in df['frame_size_raw']:                       
    d1 = re.findall("(\d+)\s*cm", i)       
    try:
        d2= float(''.join(d1))                    
    except:
        d2 = None                               
    frame.append(d2)        

# Save as new variable in the pandas data frame
df['frame_size'] = pd.Series(frame, dtype='float64')

In [29]:
# Extrahieren der numerischen Werte aus 'wheel_size_raw' und speichern in separaten Variablen (Tipp: floating point anstatt integer Variable)
wheel = []
for i in df['wheel_size_raw']:                       
    d1 = re.findall("(\d+(?:[.,]\d+)?)",i)      
    try:
        d2= float(''.join(d1))                    
    except:
        d2 = None                               
    wheel.append(d2)        

# Save as new variable in the pandas data frame
df['wheel_size'] = pd.Series(wheel, dtype='float64')

In [32]:
# Anzeigen des DataFrames nur mit den neuen Variablen und den ersten 5 Zeilen
df[['price', 'gear_count', 'battery_life', 'frame_size', 'wheel_size']].head()

   price  gear_count  battery_life  frame_size  wheel_size
0   3420          12          97.0        58.0        27.5
1   3420          12          92.0        47.0        28.0
2   3240          12          95.0        49.0        29.0
3   3670          10         143.0        46.0        27.5
4   1770          22           NaN        56.0        27.5

#### <b>Aufgabe (3): Erstellen Sie statistische Kennzahlen zu den numerischen Variablen im DataFrame.</b>
<b>Details zur Aufgabenstellung:</b>
- Berechnen Sie die statistischen Kennzahlen für die folgenden numerischen Variablen im DataFrame: price,	gear_count, battery_life,	frame_size,	wheel_size.
- Die statistische Kennzahlen, welche berechnet werden sollen sind (engl. Bezeichnungen): 
  - Count
  - Mean
  - Standard Deviation (std)
  - Minimum
  - 25th Percentile (= 1st Quartile)
  - 50th Percentile (= Median)
  - 75th Percentile (= 3rd Quartile)
  - Maximum
  - Skewness
- Stellen Sie die berechneten statistische Kennzahlen im Jupyter Notebook dar (es können auch verschiedene Ergebnistabellen angezeigt werden).<br><br>

- Tipp: 
  - Nicht alle Python - Methoden verwenden automatisch nur die numerischen Variablen. 
  - In diesen Fällen muss ein Subset mit den Spalten der numerischen Variablen erstellt werden und die Statistiken für dieses Subset berechnet werden.

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [34]:
# Einlesen der aufbereiteten Daten (damit alle auf dem gleichen Stand sind)
engine = create_engine('sqlite:///./Data/bicycle_data_prepared.db')
df = pd.read_sql_query("""SELECT * FROM bicycle_data_prepared""", con=engine)
engine.dispose()

# Columns der relevanten numerischen Variablen auswählen


# Berechnung der statistischen Kennzahlen der numerischen Spalten in 'df'
print('Summary Statistic:\n', df.describe().round(2))

# Separate Berechnung der Skewness der numerischen Spalten
cols = ['price', 'gear_count', 'battery_life', 'frame_size', 'wheel_size']
skewness = df[cols].skew().round(3)
print('\nSkewness:\n', skewness)

Summary Statistic:
           offer_id  dealer_plz  is_ebike    price  gear_count  battery_life  \
count      5000.00     5000.00   5000.00  5000.00     5000.00       3521.00
mean   54493098.28     5541.70      0.70  2772.98       12.81        119.72
std    26208138.64     2610.21      0.46   968.95        4.74         23.08
min    10001787.00     1001.00      0.00   600.00        9.00         80.00
25%    31379705.25     3269.00      0.00  2110.00       10.00        100.00
50%    54631977.50     5557.00      1.00  2900.00       11.00        120.00
75%    76752930.25     7860.25      1.00  3440.00       12.00        139.00
max    99976432.00     9999.00      1.00  5590.00       22.00        160.00

       frame_size  wheel_size
count     5000.00     5000.00
mean        52.99       28.16
std          4.34        0.62
min         46.00       27.50
25%         49.00       27.50
50%         53.00       28.00
75%         57.00       29.00
max         60.00       29.00

Skewness:
 price          -0.276
gear_count      1.315
battery_life    0.021
frame_size     -0.008
wheel_size      0.410
dtype: float64

#### <b>Aufgabe (4): Erstellen Sie eine Pivot-Tabelle mit den Mittwelwerten der numerischen Variablen pro Hersteller.</b>
<b>Details zur Aufgabenstellung:</b>
- Die Angabe zum Hersteller finden Sie in der Variable 'make'.
- Verwenden Sie die für die Mittelwertsberechnung die Variablen 'price', 'gear_count','frame_size' und 'wheel_size'.
- Stellen Sie die Pivot-Tabelle im Jupyter Notebook dar.

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [36]:
# Erstellen der Pivot-Tabelle
pivot_table = df.pivot_table(index = 'make',
                             values = ['price',
                                       'gear_count',
                                       'battery_life',
                                       'frame_size',
                                       'wheel_size'],
                                       aggfunc = 'mean').round(2)  

# Anzeigen der Pivot-Tabelle
pivot_table

             battery_life  frame_size  gear_count    price  wheel_size
make
Bulls              120.31       52.74       12.79  3257.19       28.17
Cannondale            NaN       53.02       12.49  1629.00       28.16
Cube               120.21       52.93       12.75  3201.58       28.14
Focus              119.54       53.18       12.83  3270.81       28.19
Giant              119.94       52.90       12.80  3226.61       28.13
Haibike            117.70       53.03       12.99  3269.36       28.14
Orbea              119.59       52.93       12.91  3272.39       28.15
Scott                 NaN       52.92       12.96  1655.39       28.17
Specialized        120.79       53.37       12.96  3248.30       28.18
Trek                  NaN       52.91       12.64  1627.69       28.17

#### <b>Aufgabe (5): Erstellen Sie ein Histogramm der Variable 'price'.</b>
<b>Details zur Aufgabenstellung: </b>
- Setzen Sie die Anzahl der Klassen (engl.: bins) auf den Wert 25.
- Beschriften Sie die Achsen des Histogramms, und fügen Sie einen Titel hinzu.
- Fügen Sie der Graphik ein Gitternetz (engl.: grid) hinzu.
- Zeigen Sie das Histogramm im Jupyter Notebook an. 

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [ ]:
# Erstellen des Histogramms


# Beschriftung der Achsen und Hinzufügen des Titels


# Hinzufügen des Grids


# Anzeigen der Graphik

#### <b>Aufgabe (6): Erstellen Sie einen gruppierten Boxplot mit den Preisen pro Hersteller nur für die E-Bikes.</b>
<b>Details zur Aufgabenstellung: </b>
- Erstellen Sie ein Subset der Daten nur mit E-Bikes.
- Die Information, ob es sich um ein E-Bike handelt finden Sie in der Spalte 'is_ebike' (0 = 'kein E-Bike', 1 = 'E-Bike').
- Verwenden Sie die Python Library seaborn für die Erstellung des gruppieren Boxplots.
- Die Angabe zum Hersteller (=Gruppierungsvariable) finden Sie in der Variable 'make'.
- Beschriften Sie die Achsen und geben Sie der Graphik einen Titel.
- Stellen Sie den gruppierten Boxplot im Jupyter Notebook dar.<br><br>

- Tipp: 
- Ein Subset mit den E-Bikes kann mit Hilfe von df[df['is_ebike'] == 1] erstellt werden.
- Für die Erstellung des gruppierten Boxplots können Sie Vorlagen aus der seaborn - Hilfe verwenden (vgl. Abschnitt: 'Group by a categorical variable ...'):<br><br>
  https://seaborn.pydata.org/generated/seaborn.boxplot.html


<b style="color: gray;">(max. erreichbare Punkte: 8)</b>

In [ ]:
# Subset der Daten nur mit E-Bikes erstellen


# Erstellen, Beschriften und Anzeigen eines gruppierten Boxplots der Preise pro Hersteller

#### <b>Aufgabe (7): Erstellen Sie ein Barchart mit der Anzahl Bikes pro Hersteller für alle Bikes, welche <u>keine</u> E-Bikes sind.</b>
<b>Details zur Aufgabenstellung:</b>
- Erstellen Sie ein Subset der Daten nur mit den Bikes, welche keine E-Bikes sind.
- Die Information, ob es sich um ein E-Bike handelt finden Sie in der Spalte 'is_ebike' (0 = 'kein E-Bike', 1 = 'E-Bike').
- Ergänzen Sie den Python Code unten dort wo notwendig.
- Die Angabe zum Hersteller finden Sie in der Variable 'make'.
- Im Barchart müssen die Hersteller auf der vertikalen und die Anzahl Bikes auf der horizontalen Achse abgebildet sein.
- Im Barchart müssen die Anzahl Bikes pro Hersteller der Grösse nach absteigend sortiert sein.
- Beschriften Sie die Achsen des Barcharts und geben Sie dem Barchart einen Titel.

Tipp: Ein Subset mit den Bikes, welche keine E-Bikes sind, kann mit Hilfe von df[df['is_ebike'] == 0] erstellt werden.

<b style="color: gray;">(max. erreichbare Punkte: 8)</b>

In [ ]:
# Subset der Daten nur mit den Bikes, welche keine E-Bikes sind


# Gruppierung der Daten nach 'make' und Berechnung der Anzahl Bikes pro Hersteller
df_bar = df_no_ebike['make'].value_counts().sort_values(ascending=True)

# Zusammenstellen der Werte für den Barchart
napart = list(df_bar.values)
index = list(df_bar.index.values)
y_pos = np.arange(len(index))

# Erstellen des Barcharts


# Anzeigen der Graphik

### Jupyter notebook --footer info-- (please always provide this at the end of each notebook)

In [ ]:
import os
import platform
import socket
from platform import python_version
from datetime import datetime

print('-----------------------------------')
print(os.name.upper())
print(platform.system(), '|', platform.release())
print('Datetime:', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print('Python Version:', python_version())
print('IP Address:', socket.gethostbyname(socket.gethostname()))
print('-----------------------------------')